# config\parser_config.yaml

# Directory where models will be cached
cache_dir: ".cache"

# Authentication settings
authentication:
  hf_token_env_var: "HF_TOKEN"  # Environment variable name for Hugging Face token

data_points:
  Requesting_Party:
    description: "Information about the requesting party."
    Insurance_Company:
      description: "Name of the insurance company."
    Handler:
      description: "Handler's name and contact information."
    Carrier_Claim_Number:
      description: "Unique claim number assigned by the carrier."
  Insured_Information:
    Name:
      description: "Full name of the insured individual."
    Contact_Number:
      description: "Contact number of the insured."
    Loss_Address:
      description: "Address where the loss occurred."
    Public_Adjuster:
      description: "Information about the public adjuster, if any."
    Ownership_Status:
      description: "Whether the insured is an owner or tenant of the loss location."
  Adjuster_Information:
    Adjuster_Name:
      description: "Name of the adjuster."
    Adjuster_Phone_Number:
      description: "Phone number of the adjuster."
    Adjuster_Email:
      description: "Email address of the adjuster."
    Job_Title:
      description: "Job title of the adjuster."
    Address:
      description: "Address of the adjuster."
    Policy_Number:
      description: "Policy number associated with the claim."
  Assignment_Information:
    Date_of_Loss:
      description: "Date when the loss or occurrence happened."
    Cause_of_Loss:
      description: "Cause behind the loss."
    Facts_of_Loss:
      description: "Detailed facts surrounding the loss."
    Loss_Description:
      description: "Description of the loss."
    Residence_Occupied:
      description: "Whether the residence was occupied during the loss."
    Someone_Home:
      description: "Whether someone was home at the time of damage."
    Repair_Progress:
      description: "Progress on repair or mitigation."
    Type:
      description: "Type of loss or claim."
    Inspection_Type:
      description: "Type of inspection conducted."
  Assignment_Type:
    Wind:
      description: "Wind-related damage."
    Structural:
      description: "Structural damage."
    Hail:
      description: "Hail-related damage."
    Foundation:
      description: "Foundation-related damage."
    Other:
      description: "Other types of damage. Provide details if selected."
  Additional_Details:
    description: "Any additional details or special instructions."
  Attachments:
    description: "List of attachments related to the email."

models:
  # Document parsing model
  donut:
    repo_id: "naver-clova-ix/donut-base-finetuned-cord-v2"
    task: "document"
    processor: "naver-clova-ix/donut-base-finetuned-cord-v2"
    model: "naver-clova-ix/donut-base-finetuned-cord-v2"
    device: "auto"  # Will try GPU first
    timeout: 60
    max_length: 1024
    quantize: true
    required_memory_gb: 4.0

  # Llama model configurations
  model_based_parsing:
    repo_id: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
    task: "text2text-generation"
    timeout: 45
    max_length: 1024
    quantize: true
    device: "auto"
    required_memory_gb: 35.0
    rope_scaling:
      type: "dynamic"
      factor: 8.0

  validation:
    repo_id: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
    task: "text2text-generation"
    timeout: 30
    max_length: 512
    quantize: true
    device: "auto"
    required_memory_gb: 35.0
    rope_scaling:
      type: "dynamic"
      factor: 8.0

  summarization:
    repo_id: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
    task: "text2text-generation"
    timeout: 45
    max_length: 768
    quantize: true
    device: "auto"
    required_memory_gb: 35.0
    rope_scaling:
      type: "dynamic"
      factor: 8.0
    parameters:
      max_chunk_size: 1000
      min_summary_length: 50
      max_summary_length: 150
      stride: 100
      temperature: 0.7
      top_p: 0.9
      max_retries: 3
      preprocessing:
        remove_signatures: true
        clean_headers: true
        normalize_whitespace: true

processing:
  batch_size: 2
  max_length: 1024
  device: "auto"
  fallback_to_cpu: true
  memory_optimization:
    enabled: true
    gpu_memory_fraction: 0.9  # This mofo will use up to 90% of available GPU memory

# Additional Configurations
fuzzy_threshold: 90                 # Threshold for fuzzy matching (adjust as needed)

# Known values for NER model to match (Claim numbers, insurance companies, etc.)
known_values:
  Claim Number:
    - "ABC123"
    - "XYZ789"
  Insurance Company:
    - "State Farm"
    - "Geico"
  # Add more known fields as needed...

date_formats:
  - '%m/%d/%Y'
  - '%Y-%m-%d'
  # Add more formats as needed...

boolean_values:
  positive:
    - 'yes'
    - 'true'
    - '1'
  negative:
    - 'no'
    - 'false'
    - '0'

valid_extensions:
  - '.pdf'
  - '.docx'
  - '.png'
  - '.jpg'
  - '.csv'

# Performance Enhancements
enable_amp: true  # Automatic Mixed Precision to improve GPU utilization and speed
optimize_memory: true  # Optimize memory usage to handle larger documents without performance degradation

# Logging Configuration
logging:
  level: "DEBUG"  # Set logging level to DEBUG for detailed output
  handlers:
    - "StreamHandler"
    - "FileHandler"
  file_path: "logs/parser.log"  # File path for log output
  create_logs_dir_if_not_exists: true  # Create logs directory if it does not exist
